<a href="https://colab.research.google.com/github/harshghugare80-lang/ML14/blob/main/MLnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [317]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [318]:
arr[8]


np.int64(8)

In [319]:
arr[1:5]

array([1, 2, 3, 4])

In [320]:
arr[0:5]

array([0, 1, 2, 3, 4])

Brodcasting

In [321]:
#setting a value with index range(Brodcating)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [322]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [323]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [324]:
#Change slice
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [325]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [326]:
arr_copy =arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing a 2D array


In [327]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [328]:
arr_2d[1]

array([20, 25, 30])

In [329]:
arr_2d[1,0]

np.int64(20)

In [330]:
arr_2d[1][0]

np.int64(20)

In [331]:
#slicing top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [332]:
arr_2d[2]

array([35, 40, 45])

In [333]:
arr_2d[2,:]

array([35, 40, 45])

**Fancy indexing
**

In [334]:

arr2d = np.zeros((10,10))

In [335]:
for i in range(arr2d.shape[0]):
  arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing as follows

In [336]:
arr_length = arr2d.shape[1]

In [337]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [338]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

Selection

In [339]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [340]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [342]:
bool_arr = arr>4

In [343]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [344]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [345]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [346]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])