<a href="https://colab.research.google.com/github/harshghugare80-lang/ML14/blob/main/MLnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[8]


np.int64(8)

In [15]:
arr[1:5]

array([1, 2, 3, 4])

In [16]:
arr[0:5]

array([0, 1, 2, 3, 4])

Brodcasting

In [17]:
#setting a value with index range(Brodcating)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
#Change slice
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy =arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing a 2D array


In [26]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[1]

array([20, 25, 30])

In [28]:
arr_2d[1,0]

np.int64(20)

In [29]:
arr_2d[1][0]

np.int64(20)

In [30]:
#slicing top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr_2d[2]

array([35, 40, 45])

In [32]:
arr_2d[2,:]

array([35, 40, 45])